name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 1. Entra na pasta
            cd ~/dbprivateapp
            
            # 2. Garante permiss√µes (resolve aquele erro de Permission Denied)
            echo "üîß Corrigindo permiss√µes..."
            sudo chown -R $USER:$USER .
            
            # 3. Atualiza o c√≥digo for√ßadamente
            echo "üì• Baixando atualiza√ß√µes..."
            git fetch --all
            git reset --hard origin/main
            
            # 4. Reconstr√≥i os containers
            echo "üê≥ Recriando containers..."
            docker compose down
            docker compose up -d --build
            
            # 5. Aguarda o banco subir e atualiza tabelas
            echo "‚è≥ Aguardando banco de dados..."
            sleep 15
            
            echo "üóÑÔ∏è Atualizando Banco de Dados..."
            # O -T √© importante para funcionar em modo n√£o-interativo
            docker compose exec -T api npx prisma db push
            
            echo "‚úÖ Deploy Conclu√≠do com Sucesso!"